services:
  pocket_worker:
    build:
      context: ./pocket_worker
    container_name: pocket_worker
    ports:
      - "8000:8000"
    volumes:
      - ./pocket-conf.yaml:/app/pocket-conf.yaml

  pocket_prometheus:
    image: prom/prometheus:latest
    container_name: pocket_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
  
  pocket_grafana:
    image: grafana/grafana-oss:latest
    container_name: pocket_grafana
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: ${GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH}
      GF_USERS_HOME_PAGE: ${GF_USERS_HOME_PAGE}

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning